import type { Metadata } from "next";
import { Mulish, Newsreader } from "next/font/google";
import { GlobalClickSound } from "@/app/components/GlobalClickSound";
import { SessionProvider } from "@/components/providers/session-provider";
import "./globals.css";

const newsreader = Newsreader({
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-newsreader",
});

const mulish = Mulish({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${newsreader.variable} ${mulish.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css"
        />
      </head>
      <body className={`${mulish.className} min-h-full flex flex-col`}>
        <GlobalClickSound />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
